[build]
  # Đặt thư mục functions, dù đã là mặc định, nhưng giúp đảm bảo
  functions = "functions" 

# Cấu hình cho mọi functions
[functions."*"] 
  # Tăng thời gian timeout lên 30 giây
  timeout = 30 
  # Chỉ định node bundler và external modules
  node_bundler = "esbuild"
  external_node_modules = ["@google/genai"]